### ISSUE TITLE
Js-Tests Universal app on Windows does not respond correctly to resizing

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-js#23]
1. Build and run Js-tests project in cocos2d-jsb-samples-win8.1-universal on Windows;
2. Re-size the window to half screen

Actual result: the content of the window is not adjusted correctly:

![image](https://cloud.githubusercontent.com/assets/6464667/6835459/2901aac4-d2f8-11e4-898b-cc7c61995cd1.png)

Note: After clicking on the arrow, the center of the test screen is adjusted, but still cannot see the "Main Menu" link.

**Comment by stammen** [comment]
This is due to the resolution policy in main.js being set to FIXED_HEIGHT. I changed it to SHOW_ALL for WP8 and WINRT builds

        var resolutionPolicy = (cc.sys.os == cc.sys.OS_WP8 || cc.sys.os == cc.sys.OS_WINRT) ? cc.ResolutionPolicy.SHOW_ALL : cc.ResolutionPolicy.FIXED_HEIGHT;

**Comment by stammen** [comment]
@SvDyer please verify this is fixed.

**Comment by SvDyer** [comment]
Verified, closing.
